name: fuse

on: [push, pull_request]

jobs:
  build:
    name: Build-n-Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: |
        go build -v .
        curl -L https://github.com/storj/storj/releases/latest/download/uplink_linux_amd64.zip -o uplink_linux_amd64.zip
        unzip -o uplink_linux_amd64.zip
        chmod 755 uplink
        sudo mv uplink /usr/local/bin/uplink
    - name: Setup
      run: |
        uplink --access=${{ secrets.TEST_ACCESS }} mb sj://fusetest
        head -c 100 /dev/urandom > test.txt
        uplink --access=${{ secrets.TEST_ACCESS }} cp test.txt sj://fusetest
        uplink --access=${{ secrets.TEST_ACCESS }} cp test.txt sj://fusetest/a/e
        ls -lah
        mkdir -p mt/1
        ./test-fs -access=${{ secrets.TEST_ACCESS }} -bucket="test" -mountpoint=mt/1
    - name: Test
      run: |
        ls -lah mt
        ls -lah mt/1
        ls -lah mt/1/a
        ls -lah mt/1/a/e
        cat mt/1/test.txt
        cat mt/1/a/e/test.txt
    - name: Cleanup
      run: |
        uplink --access=${{ secrets.TEST_ACCESS }} rm sj://fusetest/a/e/test.txt
        uplink --access=${{ secrets.TEST_ACCESS }} rm sj://fusetest/test.txt
        uplink --access=${{ secrets.TEST_ACCESS }} rb sj://fusetest

